### PR TITLE
added belt tooltips

### PR DESCRIPTION
**Pull request by smored**
belts now show how far they can reach as well as what shafts they can connect to.

image

### CODE REVIEW

**Comment by Electrolyte220** [comment]
Could you split the tooltip into two separate lines?
Something like this:
Max Length: %s blocks
Usable on: %s & %s shafts

**Comment by smored** [comment]
> Could you split the tooltip into two separate lines? Something like this: Max Length: %s blocks Usable on: %s & %s shafts

ofc! will have it up soon

**Comment by smored** [comment]
image

something like this?
Wanted to colour the length but couldn't figure a way to do it with arguments within a Component.translatable

**Comment by Electrolyte220** [comment]
Yes, that's perfect. If you can't figure out the coloring don't worry about it.

**Comment by smored** [comment]
Figured it out. How we feel about this?
Set the length to always be Aqua but can be dynamic too, if you want

image

**Comment by Electrolyte220** [comment]
LGTM 👍

**Pull request merged**
