### PR TITLE
Texture Overhaul

### PR DESCRIPTION
**Pull request by ULSTICK**

### CODE REVIEW

**Comment by ULSTICK** [comment]
Whoops yhat's the wrong screenshot lmao, the steel tier shouldn't be bronze lookin

**Comment by lonevox** [comment]
This seems to be the same branch that I merged to the pipes branch. Would it be possible for you to cherry-pick the non-pipe-related commits onto a separate new branch, then change your "from" branch on this PR to that new one? Either that or make a new commit on this branch removing the pipes. I'd recommend making new branches for separate features, especially when a branch has already been merged with another in-dev branch.

**Comment by ULSTICK** [comment]
I'll make a new branch

**Comment by ULSTICK** [comment]
Sorry, it seems I can't change the "from" branch in this PR, should I just make a new PR then or how should I do this?

**Comment by ULSTICK** [comment]
I'll make new PR

**Pull request closed without merging**
